Gender = st.sidebar.selectbox("Gender", options=["Female", "Male"])
    HIST_OVERWEIGHT = st.sidebar.selectbox("History of Overweight", options=["yes", "no"])
    FAVC = st.sidebar.selectbox("Frequent Consumption of Vegetables and Fruits", options=["yes", "no"])
    CAEC = st.sidebar.selectbox("Consumption of Alcohol", options=["Sometimes", "Frequently", "Always", "no"])
    SMOKE = st.sidebar.selectbox("Smoker", options=["no", "yes"])
    SCC = st.sidebar.selectbox("Self-Care", options=["no", "yes"])
    CALC = st.sidebar.selectbox("Calorie Consumption", options=["no", "Sometimes", "Frequently", "Always"])
    MTRANS = st.sidebar.selectbox("Transportation", options=["Public_Transportation", "Walking", "Automobile", "Motorbike", "Bike"])
    OBESITY_LEVEL = st.sidebar.selectbox("Obesity Level", options=["Normal_Weight", "Overweight_Level_I", "Overweight_Level_II", "Obesity_Type_I", "Insufficient_Weight", "Obesity_Type_II", "Obesity_Type_III"])